### ISSUE TITLE
Always get ''Could not resolve file name" error messages

### ISSUE THREAD

**Issue by paulhibbitts** [iusvar/grav-plugin-pdf-js#1]
Hello @iusvar ,

This plugin looks really useful (I use Google Drive to embed PDFs into Grav right now, but with mixed results), but I seem to always get the error message "Could not resolve file name"

Looking at your live demo this also seems to be the case (near the top of the page):
http://iusvar.alwaysdata.net/grav/en/blog/pdfjs

I've got my PDF is a folder called `pdfs` in my `user` folder, and here is what I am trying:

```
[pdfjs file=pdfs:cmpt-363-182-strategic-ux-design.pdf]
```

Any help greatly appreciated!

Thanks very much,
Paul

**Comment by iusvar** [comment]
Hi @paulhibbitts,

The bug in my live demo was due to putting the pdf in the wrong folder! (good programmer and bad user: schizophrenia)

Regarding your situation in addition to the already provided folder pages and folder `data`, I added the folder `pdfs`. I hope it is solved.

Thanks for the appreciation

**Comment by paulhibbitts** [comment]
Thanks very much @iusvar 👍
